
# Basic
name:               "kincent"

# URL
baseurl:            "https://kincent.tech"
permalink:          /:categories/:title

# Markdown
markdown:           rdiscount

css:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
