
# Basic
name:               "MinjunLee"

# URL
baseurl:            "https://dev-yuka05.github.io/Blog"
permalink:          /:categories/:title

# Markdown
markdown:           rdiscount

css:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
